# fly.toml app configuration file generated for dark-violet-9355 on 2023-07-29T19:17:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dark-violet-9355"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
